version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: eduapp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpass
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql